DefaultContentLanguage = "en"
author = "Shreyas Patil"
baseURL = "https://gohugo.io/"
copyright = "Copyright © 2008–2019, Shreyas Patil; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Shreyas Patil's Blog"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "All about AndroidDev is here!"
facebook = "https://facebook.com/shreyaspatil99"
github = "https://github.com/PatilShreyas"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com/@imShreyasPatil"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
